spring.application.name=core-banking-service

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/nexora
spring.datasource.username=nexora
spring.datasource.password=nexora_dev_password

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Actuator
management.endpoints.web.exposure.include=health,info